#ccache.conf was last modified on September 20, 2022 at 06:33 PM EDT by bms#
cache_dir = /tmp/ccache
sloppiness = locale,time_macros
hash_dir = false
base_dir = /home/bms
compression = true
compression_level = 5
inode_cache = true
log_file = syslog
#end
