#!/hint/bash
#makepkg.conf was last modified on September 20, 2022 at 06:33 PM EDT by bms#
CARCH="aarch64"
CHOST="aarch64-unknown-linux-gnu"
CPPFLAGS=""
CFLAGS="-march=native -O2 -pipe -fstack-protector-strong -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS=""
RUSTFLAGS="-C opt-level=2 -C target-cpu=native"
MAKEFLAGS="-j$(nproc)"
DEBUG_CFLAGS="-g -fvar-tracking-assignments"
DEBUG_CXXFLAGS="-g -fvar-tracking-assignments"
DEBUG_RUSTFLAGS="-C debuginfo=2 -C target-cpu=native"
BUILDENV=(!distcc color ccache check !sign)
OPTIONS=(strip docs libtool !staticlibs !emptydirs zipman purge !debug !lto)
PACKAGER="Ben Sutter <benjaminsutter@outlook.com>"
BUILDDIR=/tmp/makepkg
PKGDEST=~/.sources/packages
SRCDEST=~/.sources/
SRCPKGDEST=~/.sources/packages/source/
LOGDEST=~/.sources/build/aur/logs/
GPGKEY="63A85E19824320F45B09CCC9576AB3A75195A3FD"
PKGEXT=".pkg.tar.zst"
SRCEXT=".src.tar.zst"
COMPRESSZST=(zstd -c -z -q --threads=0 -)
COMPRESSXZ=(xz -c -z --threads=0 -)
COMPRESSGZ=(pigz -c -f -n)
COMPRESSBZ2=(pbzip2 -c -f)
#end
