#!/bin/bash 
#initrc was last modified on September 22, 2022 at 02:12 PM EDT by bms#
if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
dbus-update-activation-environment --systemd --all
[[ -f /home/bms/.config/x/resources ]] && xrdb -merge /home/bms/.config/x/resources
[[ -f /home/bms/.zshenv ]] && . /home/bms/.zshenv
[[ -f /home/bms/.config/zsh/.zshenv ]] && . /home/bms/.config/zsh/.zshenv
exec startxfce4
#end
