#!/bin/sh 
#initrc was last modified on September 19, 2022 at 05:26 PM EDT by bms#
if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
exec startxfce4
#end
