#aliases.zsh was last modified on October 02, 2022 at 07:20 PM EDT by bms#
alias emacs="${SCRIPTS:-$HOME/.scripts}/emacs.sh"
alias e="emacs"
alias sbcl="rlwrap sbcl --userinit ${CONFIG:-$HOME/.config}/sbcl/init.lisp"
alias src="exec zsh"
alias zshrc="${EDITOR:-emacs} ${ZDOTDIR:-$HOME/.config/zsh}/.zshrc"
alias zenv="${EDITOR:-emacs} ${ZDOTDIR:-$HOME/.config/zsh}/.zshenv"
alias zenv_="${EDITOR:-emacs} ${ZDOTDIR:-$HOME/.config/zsh}/.zshenv"
alias zlog="${EDITOR:-emacs} ${ZDOTDIR:-$HOME/.config/zsh}/.zlogin"
alias zali="${EDITOR:-emacs} ${ZDOTDIR:-$HOME/.config/zsh}/aliases.zsh"
alias zplug="${EDITOR:-emacs} ${ZDOTDIR:-$HOME/.config/zsh}/omz.zsh"
alias make="remake"
ssh_config="${CONFIG:-$HOME/.config}/ssh/config"
alias ssh="ssh -F $ssh_config"
alias scp="scp -F $ssh_config"
alias sftp="sftp -F $ssh_config"
alias icat="kitty +kitten icat"
alias neofetch="neofetch --kitty --source ${DOTFILES:-$HOME/.dotfiles}/arch.png"
alias mkdir="mkdir -p"
alias guile="guile -q -l ${CONFIG:-$HOME/.config}/guile/init.scm"
alias ls="exa --group-directories-first --icons"
alias la="ls --all"
alias ll="ls --long"
alias lla="la --long"
alias ip="ip -color=auto"
alias man="batman"
alias fdm="fdm -f ${CONFIG:-$HOME/.config}/fdm/fdm.conf"
#end
