#aliases.zsh was last modified on September 20, 2022 at 08:24 PM EDT by bms#
alias sbcl="rlwrap sbcl --userinit $CONFIG/sbcl/init.lisp"
alias src="exec zsh"
alias zshrc="$EDITOR $ZDOTDIR/.zshrc"
alias zenv="$EDITOR $ZDOTDIR/.zshenv"
alias zenv_="$EDITOR $HOME/.zshenv"
alias zlog="$EDITOR $ZDOTDIR/.zlogin"
alias zali="$EDITOR $ZDOTDIR/aliases.zsh"
alias zplug="$EDITOR $ZDOTDIR/omz.zsh"
alias make="remake"
alias pacman="pacman --color=always"
alias ssh="ssh -F $CONFIG/ssh/config"
alias icat="kitty +kitten icat"
alias emacs="$SCRIPTS/emacscheck.sh"
alias e="emacs"
alias neofetch="neofetch --kitty --source $DOTFILES/arch.png"
alias mkdir="mkdir -p"
alias guile="guile -q -l $CONFIG/guile/init.scm"
alias ls="lsd"
alias la="ls -a"
alias ll="ls -l"
alias lla="la -l"
alias ip="ip -color=auto"

#end
