font_family                 MesloLGS NF
bold_font                   MesloLGS NF Bold
italic_font                 MesloLGS NF Italic
bold_italic_font            MesloLGS NF Bold Italic
font_size                   18.0

scrollback_lines            -1

open_url_with               firefox
strip_trailing_spaces       smart

enable_audio_bell           no

remember_window_size        yes

tab_bar_style               powerline
tab_powerline_style         angled

background  	            #073642
background_opacity          0.92
